objects/Account.object
<CustomObject>
    <fields>
        <fullName>Vlocity_Demo_Image_ID__c</fullName>
        <label>Vlocity Demo Image ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlocity_Demo_Image__c</fullName>
        <formula>IF( ISBLANK(Vlocity_Demo_Image_ID__c) , 


IF( RecordType.Name = &apos;Business&apos;, &apos;/resource/VDOCommunityResources/images/profilepicbusiness.png&apos;,  &apos;/resource/VDOCommunityResources/images/profilepicconsumer.png&apos;), 


&apos;/servlet/servlet.FileDownload?file=&apos; + Vlocity_Demo_Image_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vlocity Demo Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlocity_Demo_Key__c</fullName>
        <label>Vlocity Demo Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vlocity_Demo_Name__c</fullName>
        <label>Vlocity Demo Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Status__c</fullName>
        <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Vlocity_Demo_Key__c</fullName>
        <description>Demo Contacts (Jenny Smith, Rachel Molina) should have this field populated.</description>
        <inlineHelpText>Field should be populated for demo contacts.</inlineHelpText>
        <label>Vlocity Demo Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Status__c</fullName>
        <description>Status of this Contact such as active, inactive, expired or pending. Values can be customized by the deploying company. Custom logic should also set the IsActive__c field correspondingly; e.g. inactive, expired and pending may all translate to IsActive__c = False.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <description>The type of individual. Most useful for partner employees tracked as contacts.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensed Agent</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Associate Agent</fullName>
                </value>
                <value>
                    <fullName>Managing Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <description>Formula: Value of the AccountId field.</description>
        <formula>AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Product_Channel__c</fullName>
        <label>Product Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__OmniScriptInstance__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__LastSaved__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Last Saved</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ObjectId__c</fullName>
        <label>Object Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OmniScriptSubType__c</fullName>
        <formula>TEXT(vlocity_cmt__OmniScriptId__r.vlocity_cmt__SubType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OmniScript Sub Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OmniScriptType__c</fullName>
        <formula>TEXT(vlocity_cmt__OmniScriptId__r.vlocity_cmt__Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OmniScript Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ResumeLink__c</fullName>
        <label>Resume Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Saved OmniScript</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Saved OmniScripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__Statement__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Statement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__StatementLineItem__c.object
<CustomObject>
    <description>Individual line items constituting an account&apos;s statement are imported from the client&apos;s billing system and retained here.</description>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <formula>vlocity_cmt__StatementId__r.vlocity_cmt__AccountId__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <label>Statement Line Item</label>
    <nameField>
        <displayFormat>SLI-{000000000}</displayFormat>
        <label>Statement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__VlocityAction__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__ApplicableTypes__c</fullName>
        <label>Applicable Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Aloha Home</fullName>
                </value>
                <value>
                    <fullName>Asset</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Community Home</fullName>
                </value>
                <value>
                    <fullName>Console Home</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>ContractVersion__c</fullName>
                </value>
                <value>
                    <fullName>Demo Link</fullName>
                </value>
                <value>
                    <fullName>Device Support</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Guided Help</fullName>
                </value>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Landline</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Mobile Launch Pad</fullName>
                </value>
                <value>
                    <fullName>Network &amp; Coverage</fullName>
                </value>
                <value>
                    <fullName>Note</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
                <value>
                    <fullName>vlocity_cmt__VlocityInteraction__c</fullName>
                </value>
                <value>
                    <fullName>vlocity_cmt__CustomerInteractionTopic__c</fullName>
                </value>
                <value>
                    <fullName>vlocity_cmt__CustomerInteraction__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__DisplayLabel__c</fullName>
        <label>Display Label</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__URL__c</fullName>
        <label>Target URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__VlocityIcon__c</fullName>
        <defaultValue>&apos;icon-v-document1-line&apos;</defaultValue>
        <inlineHelpText>Choose an icon from the list of icons below the Vlocity Action Detail (will not show up in Vlocity Action Edit) by copying its class name here (i.e. icon-v-document1-line). Use attachment to load custom image.</inlineHelpText>
        <label>Vlocity Icon</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Vlocity Action</label>
    <nameField>
        <label>Vlocity Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VDODemoController.cls
global class VDODemoController{

    //Home page widgets
    public Contact currentContact {get; set;}
    public Account currentAccount {get; set;}
    public Account demoAccount1 {get; set;}
    public Account demoAccount2 {get; set;}
    public Account demoAccount3 {get; set;}
    public List<Attachment> listAttachments {get;set;}
    public List<Product2> listProducts {get;set;}
    public List<vlocity_cmt__OmniScriptInstance__c> listScripts {get;set;}
    public List<vlocity_cmt__StatementLineItem__c> listUsage {get;set;}
    public List<vlocity_cmt__VlocityAction__c> listActionsSales {get;set;}
    public List<vlocity_cmt__VlocityAction__c> listActionsService {get;set;}
    public List<vlocity_cmt__VlocityAction__c> listActions {get;set;}
    public String accountKey {get;set;}
    public User currentUser {get;set;}
    public vlocity_cmt__OmniScriptInstance__c latestScript {get;set;}
    
    //Card properties
    public String layout {get;set;}
    public String sfInstanceUrl {get; private set;}
    public String currentInstanceUrlWithPath {get; private set;}
    
    public VDODemoController(){
        DemoSetup();
    }
    
    public VDODemoController(ApexPages.StandardController stdController) {
        DemoSetup();  
    }
    
    public void DemoSetup(){  
        //Widget configuration
        try{
            accountKey = ApexPages.currentPage().getParameters().get('vid') != NULL? ApexPages.currentPage().getParameters().get('vid'): 'demoaccount2';
            currentAccount = [SELECT id, name, shippingcity, recordtype.name FROM Account WHERE vlocity_demo_key__c = :accountKey LIMIT 1];
            currentContact = [SELECT firstname, lastname, name, id, phone, email FROM Contact WHERE vlocity_demo_key__c = 'democontact1' LIMIT 1];
            currentUser = [SELECT id, fullphotourl, smallphotourl, name FROM User WHERE id = :userinfo.getuserId()];
            demoAccount1 = [SELECT name, shippingcity, Vlocity_Demo_Image__c, Vlocity_Demo_Image_ID__c, Vlocity_Demo_Name__c FROM Account WHERE Vlocity_Demo_Key__c = 'demoaccount1' LIMIT 1];
            demoAccount2 = [SELECT name, shippingcity FROM Account WHERE Vlocity_Demo_Key__c = 'demoaccount2' LIMIT 1];
            demoAccount3 = [SELECT name, shippingcity FROM Account WHERE Vlocity_Demo_Key__c = 'demoaccount3' LIMIT 1];
            listProducts = [SELECT id, name FROM Product2 WHERE product_channel__c = 'Web' LIMIT 5];
            listActionsSales = [SELECT id, vlocity_cmt__DisplayLabel__c, vlocity_cmt__VlocityIcon__c, vlocity_cmt__URL__c FROM vlocity_cmt__VlocityAction__c WHERE vlocity_cmt__ApplicableTypes__c INCLUDES ('Retail') AND vlocity_cmt__URL__c != null ORDER BY vlocity_cmt__DisplayLabel__c];
            listActionsService = [SELECT id, vlocity_cmt__DisplayLabel__c, vlocity_cmt__VlocityIcon__c, vlocity_cmt__URL__c FROM vlocity_cmt__VlocityAction__c WHERE vlocity_cmt__ApplicableTypes__c INCLUDES ('Community Home') AND vlocity_cmt__URL__c != null ORDER BY vlocity_cmt__DisplayLabel__c];
            listActions = [SELECT id, vlocity_cmt__DisplayLabel__c, vlocity_cmt__VlocityIcon__c, vlocity_cmt__URL__c FROM vlocity_cmt__VlocityAction__c WHERE vlocity_cmt__ApplicableTypes__c INCLUDES ('Mobile Launch Pad') AND vlocity_cmt__URL__c != null ORDER BY vlocity_cmt__DisplayLabel__c];
            listAttachments = [SELECT id, parent.name, parentid FROM Attachment WHERE parentid IN :listProducts AND name LIKE '%TN%'];
            listScripts = [SELECT vlocity_cmt__Status__c, vlocity_cmt__OmniScriptSubType__c, vlocity_cmt__OmniScriptType__c, vlocity_cmt__ObjectId__c, vlocity_cmt__ResumeLink__c, vlocity_cmt__LastSaved__c FROM vlocity_cmt__OmniScriptInstance__c ORDER BY vlocity_cmt__LastSaved__c DESC LIMIT 10];
            listUsage = [SELECT Id, name, vlocity_cmt__AccountId__c, vlocity_cmt__Type__c, vlocity_cmt__Amount__c FROM vlocity_cmt__StatementLineItem__c WHERE vlocity_cmt__StatementId__r.vlocity_cmt__AccountId__c = :currentAccount.id AND vlocity_cmt__StatementId__r.name = 'Current Usage Statement'];
            
            for(vlocity_cmt__VlocityAction__c action : listActionsSales){
                action.vlocity_cmt__URL__c = action.vlocity_cmt__URL__c.replace('{0}', demoAccount2.id);
            }
            for(vlocity_cmt__VlocityAction__c action : listActionsService){
                action.vlocity_cmt__URL__c = action.vlocity_cmt__URL__c.replace('{0}', demoAccount2.id);
            }
            for(vlocity_cmt__VlocityAction__c action : listActions){
                action.vlocity_cmt__URL__c = action.vlocity_cmt__URL__c.replace('{0}', demoAccount2.id);
            }
            for(vlocity_cmt__OmniScriptInstance__c script : listScripts){
                script.vlocity_cmt__ResumeLink__c = script.vlocity_cmt__ResumeLink__c.replace(script.vlocity_cmt__ResumeLink__c.substring(script.vlocity_cmt__ResumeLink__c.indexOf('/apex/'), script.vlocity_cmt__ResumeLink__c.indexOf('?')), '/apex/c__VDOOmniscript');
            }
            if(listScripts.size() > 0){
                latestScript = listScripts[0];
                latestScript.vlocity_cmt__ResumeLink__c = latestScript.vlocity_cmt__ResumeLink__c.subString(latestScript.vlocity_cmt__ResumeLink__c.indexOf('/apex'));
            }
        
        }catch(Exception e){
            System.debug(e);
        }  
        //Card configuration
        layout = ApexPages.currentPage().getParameters().get('layout') != NULL? ApexPages.currentPage().getParameters().get('layout'): 'layout-grid';
        sfInstanceUrl = 'https://' + ApexPages.currentPage().getHeaders().get('X-Salesforce-Forwarded-To');
        String currentRequestUrl = System.URL.getCurrentRequestUrl().toExternalForm();
        Integer posOfApexPath = currentRequestUrl.indexOf('/apex');
        currentInstanceUrlWithPath = (posOfApexPath > -1)?currentRequestUrl.substring(0,posOfApexPath):currentRequestUrl;

    }
    
    @RemoteAction
    global static String getLatestScript(){
        List<vlocity_cmt__OmniScriptInstance__c> listScripts = [SELECT vlocity_cmt__Status__c, vlocity_cmt__OmniScriptSubType__c, vlocity_cmt__OmniScriptType__c, vlocity_cmt__ObjectId__c, vlocity_cmt__ResumeLink__c, vlocity_cmt__LastSaved__c FROM vlocity_cmt__OmniScriptInstance__c ORDER BY vlocity_cmt__LastSaved__c DESC LIMIT 10];
        for(vlocity_cmt__OmniScriptInstance__c script : listScripts){
                script.vlocity_cmt__ResumeLink__c = script.vlocity_cmt__ResumeLink__c.replace(script.vlocity_cmt__ResumeLink__c.substring(script.vlocity_cmt__ResumeLink__c.indexOf('/apex/'), script.vlocity_cmt__ResumeLink__c.indexOf('?')), '/apex/c__VDOOmniscript');
        }
        if(listScripts.size() > 0){
            vlocity_cmt__OmniScriptInstance__c latestScript = listScripts[0];
            latestScript.vlocity_cmt__ResumeLink__c = latestScript.vlocity_cmt__ResumeLink__c.subString(latestScript.vlocity_cmt__ResumeLink__c.indexOf('/apex'));
            return latestScript.vlocity_cmt__ResumeLink__c;
        }
        return '#';
    }
    
    //Create a new b2b order and redirect to the Hybrid CPQ
    global PageReference newB2BOrder(){
        vlocity_cmt__Pricelist__c p = new vlocity_cmt__Pricelist__c();
        List<vlocity_cmt__Pricelist__c> pl = [SELECT id FROM vlocity_cmt__Pricelist__c WHERE Name = '2017'];
        if(pl.size() > 0){
            p = pl[0];
        }
        Order o = new Order(AccountId = ApexPages.currentPage().getParameters().get('Id'), Status = 'Draft',  vlocity_cmt__PricelistId__c = p.id, EffectiveDate = System.TODAY(), Name = 'New Upsell Order',  VDOPriceChildItems__c = true);
        insert o;
        return new PageReference('/apex/vlocity_cmt__HybridCPQ?id=' + o.id);
    }
      
}