objects/Account.object
<CustomObject>
    <fields>
        <fullName>Vlocity_Demo_Key__c</fullName>
        <label>Vlocity Demo Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Vlocity_Demo_Key__c</fullName>
        <description>Demo Contacts (Jenny Smith, Rachel Molina) should have this field populated.</description>
        <inlineHelpText>Field should be populated for demo contacts.</inlineHelpText>
        <label>Vlocity Demo Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__OrchestrationItem__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__AutoTaskParameters__c</fullName>
        <inlineHelpText>Parameters passed to Auto Task</inlineHelpText>
        <label>Auto Task Parameters</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrchestrationItemDefinitionId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orchestration Item Definition</label>
        <referenceTo>vlocity_cmt__OrchestrationItemDefinition__c</referenceTo>
        <relationshipLabel>Orchestration Items</relationshipLabel>
        <relationshipName>OrchestrationItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrderItemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Item</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Orchestration Items (deprecated)</relationshipLabel>
        <relationshipName>OrchestrationItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SystemInterfaceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Interface</label>
        <referenceTo>vlocity_cmt__SystemInterface__c</referenceTo>
        <relationshipLabel>Orchestration Items</relationshipLabel>
        <relationshipName>SystemInterfaceId</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestration Item</label>
    <nameField>
        <label>Orchestration Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__OrchestrationItemDefinition__c.object
<CustomObject>
    <description>An orchestration item definition is a defined task that needs to happen in order to fulfill something under one or more fulfillment scenarios. Master-detail child object of Orchestration Plan Definitions.</description>
    <fields>
        <fullName>Message_Content__c</fullName>
        <label>Message Content</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AutoTaskParameters__c</fullName>
        <inlineHelpText>Parameters passed to Auto Task</inlineHelpText>
        <label>Auto Task Parameters</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SystemInterfaceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Interface</label>
        <referenceTo>vlocity_cmt__SystemInterface__c</referenceTo>
        <relationshipLabel>Orchestration Item Definitions</relationshipLabel>
        <relationshipName>OrchestrationItemDefinitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestration Item Definition</label>
    <nameField>
        <label>Orchestration Item Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Item Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__SystemInterface__c.object
<CustomObject>
    <description>Registration of an API (such as a web service) available from a given system for integrating with the system. Used by Order Management to register the fulfillment system APIs needed to drive fulfillment. Master-detail child object of System.</description>
    <label>System Interface</label>
    <nameField>
        <label>System Interface Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Interfaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VDOMobilePushNotificationAutoTask.cls
global class VDOMobilePushNotificationAutoTask implements vlocity_cmt.XOMOrchestrationInterfaces.IAutoTask {

    global void executeBatch(List<vlocity_cmt__OrchestrationItem__c> items) {
    
        for (vlocity_cmt__OrchestrationItem__c item: items) {
            
            try{
            
                List<vlocity_cmt__OrchestrationItem__c> itemReference = [SELECT vlocity_cmt__AutoTaskParameters__c, vlocity_cmt__OrderItemId__r.Order.Account.Phone, vlocity_cmt__OrderItemId__r.Order.ShipToContact.FirstName, vlocity_cmt__OrderItemId__r.Order.ShipToContact.MobilePhone, vlocity_cmt__OrderItemId__r.Order.ShipToContact.Phone, vlocity_cmt__OrderItemId__r.Order.ShipToContactId, vlocity_cmt__OrderItemId__r.Order.AccountId, vlocity_cmt__OrchestrationItemDefinitionId__r.vlocity_cmt__SystemInterfaceId__r.Name, vlocity_cmt__OrchestrationItemDefinitionId__r.Message_Content__c FROM vlocity_cmt__OrchestrationItem__c WHERE Id = :item.Id];
                
                if(itemReference.size() > 0){
                
                    Contact c;
                    if(itemReference[0].vlocity_cmt__OrderItemId__r.Order.ShipToContactId == null){
                        c = [SELECT id, Phone, FirstName, LastName, MobilePhone, HomePhone FROM Contact WHERE Vlocity_Demo_Key__c = 'democontact1' LIMIT 1];
                    }else{
                        c = itemReference[0].vlocity_cmt__OrderItemId__r.Order.ShipToContact;
                    }
                    
                    String outboundMessage = itemReference[0].vlocity_cmt__AutoTaskParameters__c;
                    outboundMessage = outboundMessage.replace('{Company}', UserInfo.getOrganizationName() );
                    outboundMessage = outboundMessage.replace('{Name}', c.FirstName);      
                
                    Map<String, Object> applePayload = Messaging.PushNotificationPayload.apple(outboundMessage, 'default', 1, null);
                    applePayload.put('deeplinking', '{objectType:Order,objectId:'+item.vlocity_cmt__orderItemId__r.orderId+'}');
                    
                    Map<String, Object> androidPayload = new Map<String, Object>();
                    androidPayload.put('message', 'android: ' + outboundMessage);
                    androidPayload.put('deeplinking', '{objectType:Order,objectId:'+item.vlocity_cmt__orderItemId__r.orderId+'}');
                    
                    // Adding recipient users to list
                    Set<String> users = new Set<String>();
                    users.add(UserInfo.getUserId());
                    
                    connected_apps.VlocityMobileNotification.send(applePayload, androidPayload, users);
                    vlocity_mobile.VlocityMobileNotification.send(applePayload, androidPayload, users);
                    
                }
                
            }catch(exception e){}
        
        }
    
    }

}