objects/Account.object
<CustomObject>
    <fields>
        <fullName>ServiceSharingType__c</fullName>
        <label>Service Sharing Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CalloutItem__c.object
<CustomObject>
    <fields>
        <fullName>CalloutContext__c</fullName>
        <label>Callout Context</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HTTPAction__c</fullName>
        <description>The action of the callout.  Get / Post / Put / Delete</description>
        <label>HTTPAction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegrationProcessingClass__c</fullName>
        <label>Integration Processing Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersistCalloutData__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Persist Callout Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SystemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System</label>
        <referenceTo>System__c</referenceTo>
        <relationshipLabel>Callout Items</relationshipLabel>
        <relationshipName>CalloutItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransformURLDRBundle__c</fullName>
        <label>TransformURL DRBundle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URI__c</fullName>
        <label>URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Callout Item</label>
    <nameField>
        <label>Callout Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callout Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CalloutMetadata__c.object
<CustomObject>
    <fields>
        <fullName>HTTPAction__c</fullName>
        <label>HTTPAction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DELETE</fullName>
                </value>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationProcessingClass__c</fullName>
        <label>Integration Processing Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OutboundDataRaptorBundleId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outbound DataRaptor Bundle</label>
        <referenceTo>vlocity_cmt__DRBundle__c</referenceTo>
        <relationshipLabel>Callout Metadata (Outbound DataRaptor Bundle)</relationshipLabel>
        <relationshipName>CalloutMetadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersistCalloutData__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Persist Callout Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ResultDataRaptorBundleId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Result DataRaptor Bundle</label>
        <referenceTo>vlocity_cmt__DRBundle__c</referenceTo>
        <relationshipLabel>Callout Metadata (Response DataRaptor Bundle)</relationshipLabel>
        <relationshipName>CalloutMetadataResponse</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SystemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System</label>
        <referenceTo>System__c</referenceTo>
        <relationshipLabel>Callout Metadata</relationshipLabel>
        <relationshipName>CalloutMetadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransformURLDataRaptorBundleId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transform URL DataRaptor Bundle</label>
        <referenceTo>vlocity_cmt__DRBundle__c</referenceTo>
        <relationshipLabel>Callout Metadata (Transform URL DataRaptor Bundle)</relationshipLabel>
        <relationshipName>CalloutMetadataTransformURL</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>URI__c</fullName>
        <label>URI</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Callout Metadata</label>
    <nameField>
        <label>Callout Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callout Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CalloutMetadataHeader__c.object
<CustomObject>
    <fields>
        <fullName>SystemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System</label>
        <referenceTo>System__c</referenceTo>
        <relationshipLabel>Callout Metadata Headers</relationshipLabel>
        <relationshipName>CalloutMetadataHeaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Callout Metadata Header</label>
    <nameField>
        <label>Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callout Metadata Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <description>The type of individual. Most useful for partner employees tracked as contacts.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensed Agent</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Associate Agent</fullName>
                </value>
                <value>
                    <fullName>Managing Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/System__c.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>System</label>
    <nameField>
        <label>System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__DRBundle__c.object
<CustomObject>
    <description>The Vlocity DataRaptor mapping bundle describes a given usage of Vlocity DataRaptor to transform data from one interface to another. The bundle contains a collection of mappings (Map Items) which define how data is transformed from the source interface to the target interface.</description>
    <fields>
        <fullName>vlocity_cmt__DRMapName__c</fullName>
        <description>The DR Map Name being used to process.</description>
        <label>DataRaptor Map Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__InputJson__c</fullName>
        <description>Saved Input format to assist in Mapping</description>
        <label>Input JSON</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__InterfaceObject__c</fullName>
        <description>Interface object used.</description>
        <label>Interface Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__TargetOutJson__c</fullName>
        <description>Expected output JSON to assist in Mapping</description>
        <label>Expected Output JSON</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <label>Interface Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vlocity DataRaptor Bundle</label>
    <nameField>
        <label>DataRaptor Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity DataRaptor Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__TriggerSetup__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>The Vlocity Trigger Setup custom setting enables or disables the Vlocity provided triggers.</description>
    <fields>
        <fullName>vlocity_cmt__IsTriggerOn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trigger On</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Setup</label>
</CustomObject>

classes/StandardIntegrationTest.cls
@isTest(SeeAllData=false)
public with sharing class StandardIntegrationTest {

	private static testMethod void testIntegrationCode(){
		vlocity_cmt__TriggerSetup__c myTrigger = new vlocity_cmt__TriggerSetup__c(Name='AllTriggers', vlocity_cmt__IsTriggerOn__c=true);
        insert myTrigger;
		System__c sys = new System__c (Name = 'Matrixx', URL__c = 'http://52.53.210.16:8080');
		insert sys;

		CalloutMetadataHeader__c hdr = new CalloutMetadataHeader__c (
			Name = 'HeaderName',
			Value__c = 'HeaderValue',
			SystemId__c = sys.Id
		);
		insert hdr;

		vlocity_cmt__DRBundle__c transformURLDR = new vlocity_cmt__DRBundle__c(
			Name = 'AccountGetOID',
			vlocity_cmt__DRMapName__c = 'AccountGetOID',
			vlocity_cmt__InputJson__c = '',
			vlocity_cmt__InterfaceObject__c = 'json' ,
			vlocity_cmt__Type__c = 'Extract (JSON)'
		);
		insert transformURLDR;

		vlocity_cmt__DRBundle__c subsCreateDR = new vlocity_cmt__DRBundle__c(
			Name = 'SubscriberCreate',
			vlocity_cmt__DRMapName__c = 'SubscriberCreate',
			vlocity_cmt__InputJson__c = '',
			vlocity_cmt__InterfaceObject__c = 'json' ,
			vlocity_cmt__Type__c = 'Extract (JSON)'
		);
		insert subsCreateDR;

		vlocity_cmt__DRBundle__c acctUpdDR = new vlocity_cmt__DRBundle__c(
			Name = 'AccountCreateResponse',
			vlocity_cmt__DRMapName__c = 'AccountCreateResponse',
			vlocity_cmt__InputJson__c = '{ "AId": "12345", "$": "MtxResponseCreate", "DomainId": 1, "ObjectId": "0-1-5-49", "Result": 0, "ResultText": "OK", "_resultCode": 0, "_resultText": "OK", "_resultType": "create", "CalloutContext": { "Id": "1234" } }',
			vlocity_cmt__InterfaceObject__c = 'json' ,
			vlocity_cmt__Type__c = 'Load (JSON)'
		);
		insert acctUpdDR;

		vlocity_cmt__DRBundle__c subBalDR = new vlocity_cmt__DRBundle__c(
			Name = 'MatrixxBalance',
			vlocity_cmt__DRMapName__c = 'MatrixxBalance',
			vlocity_cmt__InputJson__c = '{ "AId": "12345", "$": "MtxResponseCreate", "DomainId": 1, "ObjectId": "0-1-5-49", "Result": 0, "ResultText": "OK", "_resultCode": 0, "_resultText": "OK", "_resultType": "create", "CalloutContext": { "Id": "1234" } }',
			vlocity_cmt__InterfaceObject__c = 'json' ,
			vlocity_cmt__TargetOutJson__c = '{ "value": [ { "AccountKey": "", "Id": "", "Amount": "", "AvailableAmount": "", "CreditLimit": "", "DisplayQuantityUnit": "", "Name": "", "ThresholdLimit": "", "ResourceId": "" } ] }',
			vlocity_cmt__Type__c = 'Transform'
		);
		insert subBalDR;

		CalloutMetadata__c subsCreateMdt = new CalloutMetadata__c (
			Name = 'SubscriberCreate',
			SystemId__c = sys.Id,
			HTTPAction__c = 'POST',
			OutboundDataRaptorBundleId__c = subsCreateDR.Id,
			ResultDataRaptorBundleId__c = acctUpdDR.Id,
			IntegrationProcessingClass__c = 'ExternalObjectProcessing',
			URI__c = '/rsgateway/data/json/subscriber',
			PersistCalloutData__c = TRUE
			);
		insert subsCreateMdt;

		CalloutMetadata__c balanceGetMdt = new CalloutMetadata__c (
			Name = 'SubscriptionBalance-Query',
			SystemId__c = sys.Id,
			HTTPAction__c = 'GET',
			OutboundDataRaptorBundleId__c = subBalDR.Id,
			ResultDataRaptorBundleId__c = acctUpdDR.Id,
			TransformURLDataRaptorBundleId__c = transformURLDR.Id,
			IntegrationProcessingClass__c = 'ExternalObjectProcessing',
			URI__c = '/rsgateway/data/json/service/{AccountType}/ObjectId+{AccountOID}',
			PersistCalloutData__c = TRUE
			);
		insert balanceGetMdt;

		List<CalloutMetadata__c> lst = [Select Id FROM CalloutMetadata__c];
 		System.assert (lst.size() == 2);		

		Test.startTest();

		// subscriber with no contact but does have phone
		// this insert tests most of the integration code
		Account testSubs = new Account(Name = 'TestSubs', Phone = '111222333', 
			ServiceSharingType__c = 'Individual');
		insert testSubs;

		// tests sic.trasnformUri()
		CalloutItem__c callItem = new CalloutItem__c(
			Name = 'SubscriptionBalance-Query',
			SystemId__c = sys.Id,
			CalloutContext__c = '{"Id":"' + testSubs.Id + '"}',
			TransformURLDRBundle__c = 'AccountGetOID',
			URI__c = '/rsgateway/data/json/service/{AccountType}/ObjectId+{AccountOID}'
		);
		insert callItem;

		String formattedURI = 'StringToFormat';
		try {			
			StandardIntegrationClass sic = getStandardIntegrationClass(callItem);
	 		formattedURI = sic.transformUri(callItem);
		} catch (Exception e) {}
		
 		// test rest of Callout.cls
 		Callout.makeCalloutFuture(callItem.Name, '{"Id":"' + testSubs.Id + '"}');

 		Callout.makeCalloutQueue(callItem.Name, '{"Id":"' + testSubs.Id + '"}');

 		Callout.saveCallout(callItem);
 		
 	// wrong parameter for call.  It isn't working in test code. Not called anywhere yet
 	//	Callout.saveCallout(callItem.Name);

		Test.stopTest();
	}
		
	static StandardIntegrationClass getStandardIntegrationClass(CalloutItem__c callItem) {
		StandardIntegrationClass retval = new StandardIntegrationClass();

		CalloutMetadata__c calloutMdt = new CalloutMetadata__c (
			Name = 'SubscriptionBalance-Query',
			//SystemId__c = sys.Id,
			HTTPAction__c = 'GET',
			//OutboundDataRaptorBundleId__c = subBalDR.Id,
			//ResultDataRaptorBundleId__c = acctUpdDR.Id,
			//TransformURLDataRaptorBundleId__c = transformURLDR.Id,
			IntegrationProcessingClass__c = 'ExternalObjectProcessing',
			URI__c = '/rsgateway/data/json/service/{AccountType}/ObjectId+{AccountOID}',
			PersistCalloutData__c = TRUE
		);
		insert calloutMdt;
system.debug('::calloutMdt: ' + calloutMdt);
       	if (calloutMdt.IntegrationProcessingClass__c != null) {
        	// transformClass = 'SimpleTransformation'
        	String transformClass = calloutMdt.IntegrationProcessingClass__c;
			Type t = Type.forName(transformClass);

			// This is the virtual class which SimpleTransformation extends
			StandardIntegrationClass st = (StandardIntegrationClass)t.newinstance();
			retval = st;
		} 

		return retval;
	}
		//Callout.makeCalloutFuture('SubscriberCreate', item.id);
	//}
}