objects/CalloutMetadata__c.object
<CustomObject>
    <fields>
        <fullName>HTTPAction__c</fullName>
        <label>HTTPAction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DELETE</fullName>
                </value>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationProcessingClass__c</fullName>
        <label>Integration Processing Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OutboundDataRaptorBundleId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Outbound DataRaptor Bundle</label>
        <referenceTo>vlocity_cmt__DRBundle__c</referenceTo>
        <relationshipLabel>Callout Metadata (Outbound DataRaptor Bundle)</relationshipLabel>
        <relationshipName>CalloutMetadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResultDataRaptorBundleId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Result DataRaptor Bundle</label>
        <referenceTo>vlocity_cmt__DRBundle__c</referenceTo>
        <relationshipLabel>Callout Metadata (Response DataRaptor Bundle)</relationshipLabel>
        <relationshipName>CalloutMetadataResponse</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SystemId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System</label>
        <referenceTo>System__c</referenceTo>
        <relationshipLabel>Callout Metadata</relationshipLabel>
        <relationshipName>CalloutMetadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransformURLDataRaptorBundleId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transform URL DataRaptor Bundle</label>
        <referenceTo>vlocity_cmt__DRBundle__c</referenceTo>
        <relationshipLabel>Callout Metadata (Transform URL DataRaptor Bundle)</relationshipLabel>
        <relationshipName>CalloutMetadataTransformURL</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>URI__c</fullName>
        <label>URI</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Callout Metadata</label>
    <nameField>
        <label>Callout Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callout Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/System__c.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>System</label>
    <nameField>
        <label>System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__DRBundle__c.object
<CustomObject>
    <description>The Vlocity DataRaptor mapping bundle describes a given usage of Vlocity DataRaptor to transform data from one interface to another. The bundle contains a collection of mappings (Map Items) which define how data is transformed from the source interface to the target interface.</description>
    <label>Vlocity DataRaptor Bundle</label>
    <nameField>
        <label>DataRaptor Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity DataRaptor Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CalloutTest.cls
@isTest
private with sharing class CalloutTest {
	
	@isTest static void TestCallout() {
		// Implement test code
		System__c sys = new System__c();
		sys.Name = 'TestSystem';
		sys.URL__C = 'http://www.google.com';
		insert sys;
		List<vlocity_cmt__drbundle__c> drb = [select id from vlocity_cmt__drbundle__c];
		CalloutMetadata__c cmd = new CalloutMetadata__c();
		cmd.Name = 'testCallout';
		cmd.HTTPAction__c = 'Post';
//		cmd.IntegrationProcessingClass__c = 'StandardInterfaceClassXMLOut';
		cmd.OutboundDataRaptorBundleId__c = 'a0x0P00000BMf7gQAD';
		cmd.ResultDataRaptorBundleId__c = 'a0x0P00000BMf7gQAD';
		cmd.TransformURLDataRaptorBundleId__c = 'a0x0P00000BMf7gQAD';
		cmd.SystemId__c = sys.Id;
		cmd.URI__c = '/12345/{test1}';
		insert cmd;

		String temp = '{"Id":"00112345678912"}';
		Object o = JSON.deserializeUntyped(temp);
		System.debug('BBBBB before send ' + temp);

		callout.makeCallout('testCallout',o);
	}
/*	
	@isTest static void TestMakeCallout() {
		String temp = '{"Id" : "0010P00001oI6RG"}';
		Object o = JSON.deserializeUntyped(temp);
		System.debug('BBBBB before send ' + temp);
		callout.makeCallout('SubscriberGetBalances', o);
	}
*/	
}