objects/CalloutItem__c.object
<CustomObject>
    <fields>
        <fullName>CalloutBody__c</fullName>
        <label>Callout Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ResponseMessageRaw__c</fullName>
        <label>Response Message Raw</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ResponseMessage__c</fullName>
        <label>Response Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Callout Item</label>
    <nameField>
        <label>Callout Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Callout Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StandardInterfaceClassXMLOut.cls
global virtual with sharing class StandardInterfaceClassXMLOut extends StandardIntegrationClass {

	//do nothing
	/*
	global void preOut(CalloutItem__c callout) {
	}
	*/

	global virtual override void postOutbound(CalloutItem__c callout) {
		String body = callout.CalloutBody__c;
		String newBody = JsonToXml.convertJsonToXml(body);
		callout.CalloutBody__c = newBody;
	}

	global virtual override void preResult(CalloutItem__c callout) {
		String body = callout.ResponseMessageRaw__c;
		//String newBody = XmlToJson.convertXMLToJson(body);
		Map<String,Object> temp = XMLToJson.ParseXML(body);
		Object temp2 = temp.get('json');
		callout.ResponseMessage__c = JSON.serialize(temp2);	
	}

	//do nothing
	/*
	global void postIn(CalloutItem__c callout) {
		
	}
	*/
}