objects/Order.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__OneTimeTotal__c</fullName>
        <label>Total: One Time Charges</label>
        <summarizedField>OrderItem.vlocity_cmt__OneTimeTotal__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrchestrationPlanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orchestration Plan</label>
        <referenceTo>vlocity_cmt__OrchestrationPlan__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__RecurringTotal__c</fullName>
        <label>Total: Monthly Charges</label>
        <summarizedField>OrderItem.vlocity_cmt__RecurringTotal__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__FulfilmentRequest__c.object
<CustomObject>
    <description>Representation for backend orders (CFS Orders, Logistics Orders, Billing Update Requests, etc)</description>
    <fields>
        <fullName>vlocity_cmt__OrderId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Fulfilment Requests</relationshipLabel>
        <relationshipName>FulfilmentRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__orchestrationPlanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orchestration Plan</label>
        <referenceTo>vlocity_cmt__OrchestrationPlan__c</referenceTo>
        <relationshipLabel>Fulfilment Requests</relationshipLabel>
        <relationshipName>FulfilmentRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fulfilment Request</label>
    <nameField>
        <displayFormat>FR{0000000}</displayFormat>
        <label>Fulfilment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfilment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__OrchestrationItem__c.object
<CustomObject>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ExecutionLog__c</fullName>
        <label>Execution Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__LeadTimeCompleted__c</fullName>
        <label>Lead Time (Completed)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__LeadTimeRunning__c</fullName>
        <label>Lead Time (Running)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrchestrationItemDefinitionId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orchestration Item Definition</label>
        <referenceTo>vlocity_cmt__OrchestrationItemDefinition__c</referenceTo>
        <relationshipLabel>Orchestration Items</relationshipLabel>
        <relationshipName>OrchestrationItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrchestrationPlanId__c</fullName>
        <label>Orchestration Plan</label>
        <referenceTo>vlocity_cmt__OrchestrationPlan__c</referenceTo>
        <relationshipLabel>Orchestration Items</relationshipLabel>
        <relationshipName>OrchestrationItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Fatally Failed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SystemInterfaceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Interface</label>
        <referenceTo>vlocity_cmt__SystemInterface__c</referenceTo>
        <relationshipLabel>Orchestration Items</relationshipLabel>
        <relationshipName>SystemInterfaceId</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__TimestampCompleted__c</fullName>
        <label>Timestamp (Completed)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__TimestampReady__c</fullName>
        <label>Timestamp (Ready)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__TimestampRunning__c</fullName>
        <label>Timestamp (Running)</label>
        <type>DateTime</type>
    </fields>
    <label>Orchestration Item</label>
    <nameField>
        <label>Orchestration Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__OrchestrationItemDefinition__c.object
<CustomObject>
    <description>An orchestration item definition is a defined task that needs to happen in order to fulfill something under one or more fulfillment scenarios. Master-detail child object of Orchestration Plan Definitions.</description>
    <fields>
        <fullName>vlocity_cmt__SystemId__c</fullName>
        <formula>vlocity_cmt__SystemInterfaceId__r.vlocity_cmt__SystemId__c</formula>
        <label>Dependency Plan Definition</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SystemInterfaceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Interface</label>
        <referenceTo>vlocity_cmt__SystemInterface__c</referenceTo>
        <relationshipLabel>Orchestration Item Definitions</relationshipLabel>
        <relationshipName>OrchestrationItemDefinitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestration Item Definition</label>
    <nameField>
        <label>Orchestration Item Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Item Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__OrchestrationPlan__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__OrderId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Orchestration Plans</relationshipLabel>
        <relationshipName>OrchestrationPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Orchestration Plan</label>
    <nameField>
        <displayFormat>Plan{0000000}</displayFormat>
        <label>Orchestration Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orchestration Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__System__c.object
<CustomObject>
    <description>Registration of an external system to enable integration with the system. Used by Vlocity Order Management to register the fulfillment systems necessary to drive order fulfillment.</description>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Online__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Online</label>
        <type>Checkbox</type>
    </fields>
    <label>System</label>
    <nameField>
        <label>System Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__SystemInterface__c.object
<CustomObject>
    <description>Registration of an API (such as a web service) available from a given system for integrating with the system. Used by Order Management to register the fulfillment system APIs needed to drive fulfillment. Master-detail child object of System.</description>
    <fields>
        <fullName>vlocity_cmt__SystemId__c</fullName>
        <label>System</label>
        <referenceTo>vlocity_cmt__System__c</referenceTo>
        <relationshipLabel>System</relationshipLabel>
        <relationshipName>SystemInterfaces</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Interface</label>
    <nameField>
        <label>System Interface Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Interfaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VDOXOMDemoDashboardController.cls
public class VDOXOMDemoDashboardController{

    public void VDOXOMDemoDashboardController(){   
    }
    
    @RemoteAction
    public static vlocity_cmt__OrchestrationItem__c getNotifications(String itemId){ 
        return [SELECT id, Name, response__c, request__c, vlocity_cmt__TimestampReady__c, vlocity_cmt__TimestampRunning__c, vlocity_cmt__TimestampCompleted__c, vlocity_cmt__LeadTimeRunning__c, vlocity_cmt__LeadTimeCompleted__c, vlocity_cmt__ExecutionLog__c FROM vlocity_cmt__OrchestrationItem__c WHERE id = :itemId LIMIT 1][0];
    }
    
    @RemoteAction
    public static List<vlocity_cmt__OrchestrationPlan__c> getOrchestrationPlans(){   
        return [SELECT id, name, vlocity_cmt__OrderId__c, vlocity_cmt__OrderId__r.OrderNumber, vlocity_cmt__OrderId__r.EffectiveDate, vlocity_cmt__OrderId__r.Account.Name, vlocity_cmt__OrderId__r.Account.PhotoURL, vlocity_cmt__OrderId__r.vlocity_cmt__RecurringTotal__c, vlocity_cmt__OrderId__r.vlocity_cmt__OneTimeTotal__c FROM vlocity_cmt__OrchestrationPlan__c ORDER BY createddate ASC];     
    }
    
    @RemoteAction
    public static List<vlocity_cmt__OrchestrationItem__c> getOrchestrationPlanItems(String planId){   
        return [SELECT id, name, vlocity_cmt__OrchestrationItemDefinitionId__r.RecordType.Name, vlocity_cmt__State__c, vlocity_cmt__LeadTimeRunning__c, vlocity_cmt__LeadTimeCompleted__c, vlocity_cmt__SystemInterfaceId__r.vlocity_cmt__SystemId__r.Id FROM vlocity_cmt__OrchestrationItem__c WHERE vlocity_cmt__OrchestrationPlanId__c = :planId ORDER BY createddate];     
    }
    
    @RemoteAction
    public static List<vlocity_cmt__System__c> getOrchestrationPlanSystems(String planId){   
        Set<Id> theSystemIds = new Set<Id>();
        for(vlocity_cmt__OrchestrationItem__c theItem : [SELECT id, name, vlocity_cmt__SystemInterfaceId__r.vlocity_cmt__SystemId__r.Id FROM vlocity_cmt__OrchestrationItem__c WHERE vlocity_cmt__OrchestrationPlanId__c = :planId AND vlocity_cmt__SystemInterfaceId__c != NULL]){
            theSystemIds.add(theItem.vlocity_cmt__SystemInterfaceId__r.vlocity_cmt__SystemId__r.Id);
        }     
        return [SELECT id, name, image__c, online__c FROM vlocity_cmt__System__c WHERE Id IN :theSystemIds];     
    }

    @RemoteAction
    public static void toggleSystem(String systemid, Boolean online){
        vlocity_cmt__System__c theSystem = [SELECT id, name, image__c, online__c FROM vlocity_cmt__System__c WHERE Id = :systemid LIMIT 1][0];
        theSystem.Online__c = online;
        update theSystem;   
    }

    @RemoteAction
    public static void retryItem(String itemid){
        vlocity_cmt__OrchestrationItem__c theItem =  [SELECT id, name, vlocity_cmt__State__c FROM vlocity_cmt__OrchestrationItem__c WHERE id = :itemid][0];     
        theItem.vlocity_cmt__State__c = 'Ready';
        update theItem;   
    }

    @RemoteAction 
    public static void DeleteOrchestrationPlans(){   
        delete [select id from vlocity_cmt__OrchestrationDependency__c];
        delete [select id from vlocity_cmt__OrchestrationItem__c];
        delete [select id from vlocity_cmt__OrchestrationPlan__c];
        delete [select id from vlocity_cmt__FulfilmentRequestDecompRelationship__c];
        delete [select id from vlocity_cmt__FulfilmentRequest__c];
    }

}