objects/Order.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__OrchestrationPlanId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orchestration Plan</label>
        <referenceTo>vlocity_cmt__OrchestrationPlan__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__OrchestrationItem__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__OrchestrationPlanId__c</fullName>
        <label>Orchestration Plan</label>
        <referenceTo>vlocity_cmt__OrchestrationPlan__c</referenceTo>
        <relationshipLabel>Orchestration Items</relationshipLabel>
        <relationshipName>OrchestrationItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Fatally Failed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Skipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Orchestration Item</label>
    <nameField>
        <label>Orchestration Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__OrchestrationPlan__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__OrderId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Orchestration Plans</relationshipLabel>
        <relationshipName>OrchestrationPlans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Orchestration Plan</label>
    <nameField>
        <displayFormat>Plan{0000000}</displayFormat>
        <label>Orchestration Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orchestration Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VPLCreatePlan.cls
global with sharing class VPLCreatePlan implements vlocity_cmt.VlocityOpenInterface
{
global VPLCreatePlan() { }

    global Boolean invokeMethod(String methodName, Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Boolean result = true;
        try
        {
            if (methodName.equals('createPlanMethod'))
            {
                createPlanMethod(inputMap,outMap,options);
            }
            else if (methodName.equals('startPlanByOrderId'))
            {
                startPlanByOrderId(inputMap,outMap,options);
            }
            
            else{
                  result = false;
                 } 
        } 
        catch(Exception e)
        {
            System.debug('invokeMethod -> exception: '+e);
            result = false;
        }
        
        return result;
    }
    
      void createPlanMethod(Map<String, Object> inputMap, Map<String, Object> outMap,Map<String,Object> options)
      {
          String sOrderId = (String)inputMap.get('OrderId');
          System.debug('createPlanMethod::OrderId:->'+sOrderId);
          
          String PlanId = vlocity_cmt.SimpleDecompositionController.decomposeAndCreatePlan(sOrderId);
          
          //have to love cart horse bs.
          //vlocity_cmt__OrchestrationPlan__c Plan= [Select Name FROM vlocity_cmt__OrchestrationPlan__c WHERE Id=:PlanId];
          outMap.put('PlanName',PlanId);
          
      } 
      
     
      
      void startPlanByOrderId(Map<String, Object> inputMap, Map<String, Object> outMap,Map<String,Object> options)
      {
      
          String sOrderId = (String)inputMap.get('OrderId');
          System.debug('startPlanByOrderId::OrderId:->'+sOrderId);
          List<vlocity_cmt__orchestrationplan__c> plan = [select id from vlocity_cmt__orchestrationplan__c where vlocity_cmt__OrderId__c = :sOrderId];
          
          if(plan.size() == 1)
          {
              List<vlocity_cmt__OrchestrationItem__c> itemsToStart = [select id, CreatedBy.Name,Name,vlocity_cmt__State__c 
                                      from vlocity_cmt__OrchestrationItem__c 
                                      where vlocity_cmt__OrchestrationPlanId__c  = :plan[0].Id 
                                      and Name in('Start Order','Start Consumer Order')
                                      and vlocity_cmt__State__c = 'Pending'];
                                      
              if(itemsToStart.size() == 1)
              {
                  itemsToStart[0].vlocity_cmt__State__c = 'Completed';
                  update itemsToStart;
                  outMap.put('PlanStarted','true');
              }
          }                                      
      }
    }